export const peers = [
    {
      id: "current-user",
      name: "Anonymous",
      isVideoEnabled: true,
      isAudioEnabled: true,
      isCurrentUser: true,
    },
    {
      id: "user-2",
      name: "Alice Johnson",
      isVideoEnabled: true,
      isAudioEnabled: true,
      isCurrentUser: false,
    },
    {
      id: "user-3",
      name: "Bob Smith",
      isVideoEnabled: false,
      isAudioEnabled: true,
      isCurrentUser: false,
    },
    {
      id: "user-4",
      name: "Carol Davis",
      isVideoEnabled: true,
      isAudioEnabled: false,
      isCurrentUser: false,
    },
    {
     id: "user-5",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-6",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-7",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-8",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-9",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-10",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-11",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-12",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-13",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
    {
     id: "user-15",
     name: "Carol Davis",
     isVideoEnabled: true,
     isAudioEnabled: false,
     isCurrentUser: false,
    },
]